import{a as q,S as P,i as f}from"./assets/vendor-5401a4b0.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const c of t.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&r(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const d=document.querySelector(".gallery-o");function m(o,n){const s=o.map(({largeImageURL:r,webformatURL:e,tags:t,likes:c,views:x,comments:$,downloads:M})=>`
        <div class="gallery">
            <a href="${r}">
            <img src="${e}" alt="${t}" title="${t}" width="380" height="220" />
            <ul class="info-cards-container">
                <li class="info-cards-elements">likes<span>${c}</span></li>
                <li class="info-cards-elements">views<span>${x}</span></li>
                <li class="info-cards-elements">comments<span>${$}</span></li>
                <li class="info-cards-elements">downloads<span>${M}</span></li>
            </ul>
            </a>
        </div>
        `).join("");if(n===1)d.innerHTML=s;else{d.insertAdjacentHTML("beforeend",s);const r=d.lastElementChild.getBoundingClientRect().height;scrollBy({behavior:"smooth",top:r*3})}}async function p(o,n){try{const s="42424645-ecd3f1048329df1dec069e6a8",r=await q.get("https://pixabay.com/api/",{params:{key:s,q:o,image_type:"photo",orientation:"horizontal",safesearch:"true",page:n,per_page:"15"}});if(r.data.total===0)throw new Error("No images found");return r.data}catch(s){throw s}}const y=document.querySelector(".search-form"),g=document.querySelector(".gallery-o"),L=document.querySelector(".loader"),w=document.querySelector(".loader2"),l=document.querySelector(".more-btn"),v=new P(".gallery-o a",{captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionPosition:"bottom",animation:250});let u,i,a;function O(){b(),y.addEventListener("submit",B)}async function B(o){o.preventDefault(),H(),g.innerHTML="",i=1,u=y.querySelector(".input-search").value;try{const n=await p(u,i);m(n.hits,i),v.refresh(),a=Math.ceil(n.totalHits/15)}catch(n){T(n)}finally{b(),h()}}document.addEventListener("DOMContentLoaded",O);function T(o){a=void 0,h(),g.innerHTML="",f.show({message:`❌ "${o}". Please try again!`,color:"red",position:"topRight",maxWidth:"400px"})}function H(){L.style.display="block"}function b(){L.style.display="none"}function R(){w.classList.remove("hidden")}function S(){w.classList.add("hidden")}l.addEventListener("click",async()=>{i++,R();try{const o=await p(u,i);m(o.hits,i),v.refresh(),i>1&&(S(),h())}catch(o){f.show({message:`"${o}". UPS something wrong!`,color:"red",position:"topRight",maxWidth:"400px"})}});function C(){i===a&&(a=void 0,S(),E(),f.show({message:`❌ "We're sorry, but you've reached the end of search results."`,color:"red",position:"topRight",maxWidth:"400px"}))}l.addEventListener("click",C);function D(){l.classList.remove("hidden")}function E(){l.classList.add("hidden")}function h(){i>=a||a===void 0?E():D()}
//# sourceMappingURL=commonHelpers.js.map
